export type Language = "sq" | "en";
export const languageCookie = "kreu-language";

// English is also the stable message key. Never translate stored form values,
// project slugs, customer input, contact addresses or third-party brand names.
export const albanian: Record<string, string> = {
  "KREU WEB. Built for progress.": "KREU WEB. Ndërtuar për progres.",
  "Language": "Gjuha",
  "KREU WEB, home": "KREU WEB, kreu",
  "Primary navigation": "Navigimi kryesor",
  "Mobile navigation": "Navigimi në celular",
  "Footer navigation": "Navigimi në fund të faqes",
  "Work": "Projektet",
  "Services": "Shërbimet",
  "Contact": "Kontakt",
  "Open menu": "Hap menunë",
  "Close menu": "Mbyll menunë",
  "Close": "Mbyll",
  "Menu": "Menu",
  "Book a discovery call": "Rezervo një konsultë",
  "Build a business": "Ndërto një biznes",
  "people take seriously.": "që merret seriozisht.",
  "We articulate your business with greater clarity, authority and credibility. It is perceived at the level it deserves.": "E artikulojmë biznesin tuaj me më shumë qartësi, autoritet dhe besueshmëri. Kështu perceptohet në nivelin që meriton.",
  "View our work": "Shiko projektet",
  "Built for progress": "Ndërtuar për progres",
  "Every decision should serve the business.": "Çdo vendim duhet t’i shërbejë biznesit.",
  "Integrated strategy, design and technology for clearer positioning, sharper differentiation and greater competitive relevance.": "Strategji, dizajn dhe teknologji të integruara për një pozicionim më të qartë, diferencim më të dallueshëm dhe relevancë më të lartë në treg.",
  "Strategy & Design": "Strategji & Dizajn",
  "Web Development": "Web Development",
  "Marketing & SEO": "Marketing & SEO",
  "Software Systems": "Sisteme Software",
  "Connected services workflow": "Shërbime që funksionojnë së bashku",
  "Authority. Differentiation. Growth.": "Autoritet. Diferencim. Rritje.",
  "For the next stage.": "Për etapën e radhës.",
  "Make your business harder to ignore.": "Bëje biznesin tënd të pamundur për t’u anashkaluar.",
  "A considered digital presence designed to consolidate trust, increase relevance and open new opportunities for the business.": "Një prezencë digjitale e menduar për të konsoliduar besimin, për të rritur relevancën dhe për të hapur mundësi të reja për biznesin.",
  "Design · Development · Growth · Software": "Dizajn · Zhvillim · Rritje · Software",
  "All rights reserved.": "Të gjitha të drejtat e rezervuara.",
  "For businesses defined by ambition.": "Për biznese me ambicie.",
  "Kreu Web on Instagram": "Kreu Web në Instagram",
  "Your next chapter": "Hapi juaj i radhës",
  "Selected website concepts": "Projekte të përzgjedhura",
  "Preview": "Shiko projektin",
  "Design concept": "Koncept dizajni",
  "Residential Real Estate": "Prona rezidenciale",
  "Mobile App / Software": "Aplikacion Mobile / Software",
  "Med Spa": "Klinikë estetike",
  "Hospitality": "Hoteleri & Restorante",
  "Car Rental": "Makina me qira",
  "A refined digital experience for modern residential developments.": "Një prezantim digjital i kuruar për rezidenca bashkëkohore.",
  "A considered mobile app concept for focused work, daily planning, and a little more clarity.": "Një aplikacion për më shumë përqendrim, planifikim të qartë dhe ditë më të organizuara.",
  "A calm, clinically precise experience for modern aesthetic care.": "Një përvojë e qetë dhe e qartë, që pasqyron kujdesin dhe saktësinë e mjekësisë estetike.",
  "A cinematic reservation experience built around appetite and atmosphere.": "Një përvojë rezervimi që përcjell shijen dhe atmosferën e restorantit.",
  "A booking experience engineered around performance and exceptional cars.": "Një përvojë rezervimi e kuruar për makina me performancë të jashtëzakonshme.",
  "Contemporary luxury residence architecture": "Arkitekturë bashkëkohore e një rezidence luksoze",
  "Residences": "Rezidencat",
  "Architecture": "Arkitektura",
  "Neighbourhood": "Zona",
  "Private viewings": "Vizita private",
  "Private residences · Tirana": "Rezidenca private · Tiranë",
  "Life, framed": "Jeta, në harmoni",
  "by architecture.": "me arkitekturën.",
  "Explore availability": "Shih rezidencat e lira",
  "Residence 04": "Rezidenca 04",
  "Three bedrooms · 186 m²": "Tri dhoma gjumi · 186 m²",
  "Now selling": "Në shitje",
  "Completion · Autumn 2027": "Përfundon · Vjeshtë 2027",
  "Still focus and planning app on a graphite smartphone in a softly lit charcoal workspace": "Aplikacioni Still për përqendrim dhe planifikim, në një telefon në ambient pune me dritë të butë",
  "Treatments": "Trajtimet",
  "Doctors": "Mjekët",
  "Philosophy": "Filozofia",
  "Book a consultation": "Rezervo një konsultë",
  "Skin intelligence · Tirana": "Kujdes për lëkurën · Tiranë",
  "Results you see.": "Rezultate të dukshme.",
  "Restraint you feel.": "Bukuri e natyrshme.",
  "Aesthetic medicine led by doctors and designed around skin health, natural expression and lasting confidence.": "Mjekësi estetike me shëndetin e lëkurës në qendër. Kujdes profesional që ruan shprehjen tuaj natyrale.",
  "Meet your skin": "Njih lëkurën tënde",
  "Portrait focused on natural skin": "Portret që vë në pah bukurinë natyrale të lëkurës",
  "Precision peel": "Peeling i personalizuar",
  "45 min · From €120": "45 min · Nga €120",
  "Contemporary fine dining room": "Ambient restoranti bashkëkohor",
  "Menu   Cellar   Story": "Menu   Verërat   Historia",
  "Reserve a table": "Rezervo një tavolinë",
  "Tirana · Dinner, Tuesday—Sunday": "Tiranë · Darkë, e martë—e diel",
  "The night": "Mbrëmja",
  "has a flavour.": "ka shijen e saj.",
  "Discover the menu": "Zbulo menunë",
  "Chef’s table": "Në tryezën e shefit",
  "Eight seasonal courses": "Tetë pjata të stinës",
  "Rruga e Durrësit, Tirana": "Rruga e Durrësit, Tiranë",
  "From 18:30 until late": "Nga ora 18:30 deri vonë",
  "Black performance car in motion": "Makinë sportive e zezë në lëvizje",
  "Fleet": "Makinat",
  "Membership": "Anëtarësimi",
  "Destinations": "Destinacionet",
  "Reserve": "Rezervo",
  "Porsche Panamera Turbo · Tirana": "Porsche Panamera Turbo · Tiranë",
  "Performance,": "Performancë,",
  "on your terms.": "sipas ritmit tënd.",
  "Configure your drive": "Zgjidh udhëtimin tënd",
  "From €680 / day": "Nga €680 / ditë",
  "24 / 7 concierge": "Asistencë 24 / 7",
  "Also available": "Gjithashtu në dispozicion",
  "First class.": "Klas i parë.",
  "Every mile.": "Në çdo kilometër.",
  "Your next drive": "Udhëtimi yt i radhës",
  "Explore the fleet": "Shih makinat",
  "Play First Class motion": "Luaj animacionin e First Class",
  "Pause First Class motion": "Ndalo animacionin e First Class",
  "Opening booking…": "Po hapet rezervimi…",
  "Close booking": "Mbyll rezervimin",
  "Discovery call": "Konsultë",
  "Confirmed": "Konfirmuar",
  "Booking progress": "Ecuria e rezervimit",
  "What’s your full name?": "Si quheni?",
  "What’s your email address?": "Cili është emaili juaj?",
  "What’s your business called?": "Si quhet biznesi juaj?",
  "Do you currently have a website?": "A keni aktualisht një website?",
  "What’s your current monthly business revenue?": "Sa është xhiroja mujore e biznesit tuaj?",
  "What should we know before the call?": "Çfarë duhet të dimë para se të flasim?",
  "Choose a time that works.": "Zgjidhni orarin që ju përshtatet.",
  "Full name": "Emri dhe mbiemri",
  "Your full name": "Emri dhe mbiemri juaj",
  "Email address": "Adresa e emailit",
  "Business name": "Emri i biznesit",
  "Your business name": "Emri i biznesit tuaj",
  "Yes": "Po",
  "No": "Jo",
  "Website URL": "Adresa e website-it",
  "yourbusiness.com": "biznesijuaj.com",
  "you@business.com": "ju@biznesi.com",
  "Current monthly business revenue": "Të ardhurat mujore të biznesit",
  "Under €10k": "Nën €10k",
  "€10k–€50k": "€10.000–€50.000",
  "€50k–€100k": "€50.000–€100.000",
  "€100k+": "€100.000+",
  "A little context": "Pak kontekst",
  "Optional": "Opsionale",
  "A few lines about the business, what’s changing, and what you want Kreu to help you achieve.": "Na tregoni shkurt për biznesin, çfarë po ndryshon dhe çfarë doni që Kreu t’ju ndihmojë të arrini.",
  "Times shown in": "Oraret sipas zonës",
  "Finding available times…": "Po kërkojmë oraret e lira…",
  "Scheduling is temporarily unavailable.": "Rezervimi online është përkohësisht i padisponueshëm.",
  "We couldn’t load available times.": "Nuk arritëm t’i shfaqim oraret e lira.",
  "There are no open times in the next 60 days.": "Nuk ka orare të lira gjatë 60 ditëve të ardhshme.",
  "Email": "Na shkruani në",
  "to arrange a call.": "për të lënë një takim.",
  "Your details haven’t been sent.": "Të dhënat tuaja nuk janë dërguar.",
  "Check again": "Provo sërish",
  "Back": "Kthehu",
  "Confirming your call…": "Po konfirmojmë konsultën…",
  "Book discovery call": "Rezervo konsultën",
  "Continue": "Vazhdo",
  "Your details are sent securely when you book. No mailing lists.": "Të dhënat dërgohen në mënyrë të sigurt vetëm kur rezervoni. Pa emaile promocionale.",
  "A few details. Then we talk about where your business can go next.": "Disa detaje. Pastaj flasim për hapin e radhës të biznesit tuaj.",
  "A considered start to something better.": "Një hap i menduar mirë.",
  "You’re booked.": "Konsulta u rezervua.",
  "Your discovery call is confirmed. Check your email for the invitation.": "Konfirmimin dhe ftesën i gjeni në email.",
  "The call link isn’t available yet. Check your invitation email or contact hello@kreuweb.com before the call.": "Linku i takimit nuk është ende gati. Kontrolloni ftesën në email ose na shkruani në hello@kreuweb.com para takimit.",
  "Join call": "Bashkohu në takim",
  "Back to Kreu": "Kthehu te Kreu",
  "Previous month": "Muaji i kaluar",
  "Next month": "Muaji i ardhshëm",
  "Choose a date": "Zgjidhni datën",
  "Choose a time": "Zgjidhni orarin",
  "Available times": "Oraret e lira",
  "There are no available times to select.": "Për momentin nuk ka orare të lira.",
  "Please enter your full name.": "Shkruani emrin dhe mbiemrin.",
  "Please enter a valid email address.": "Shkruani një adresë emaili të vlefshme.",
  "Please enter your business name.": "Shkruani emrin e biznesit.",
  "Choose Yes or No to continue.": "Zgjidhni Po ose Jo për të vazhduar.",
  "Enter your website address, for example yourbusiness.com.": "Shkruani adresën e website-it, për shembull biznesijuaj.com.",
  "Choose a revenue range.": "Zgjidhni nivelin e të ardhurave.",
  "Please keep your notes under 2,000 characters.": "Ju lutemi, shkruani jo më shumë se 2 000 karaktere.",
  "Choose an available date and time to book your call.": "Zgjidhni një datë dhe orar të lirë për konsultën.",
  "That time was just booked. Please choose another available time.": "Ky orar sapo u rezervua. Ju lutemi, zgjidhni një orar tjetër.",
  "Your request is awaiting confirmation. Please check your email before trying again.": "Kërkesa juaj është në pritje të konfirmimit. Kontrolloni emailin para se të provoni sërish.",
  "We couldn’t confirm your booking. Please retry to check this request. If this continues, email hello@kreuweb.com.": "Nuk arritëm ta konfirmojmë rezervimin. Provoni sërish. Nëse problemi vazhdon, na shkruani në hello@kreuweb.com.",
};

export function translate(language: Language, message: string): string {
  return language === "sq" ? albanian[message] ?? message : message;
}

const monthsSq = ["janar", "shkurt", "mars", "prill", "maj", "qershor", "korrik", "gusht", "shtator", "tetor", "nëntor", "dhjetor"];
const weekdaysSq = ["E diel", "E hënë", "E martë", "E mërkurë", "E enjte", "E premte", "E shtunë"];
export function calendarWeekdays(language: Language) {
  return language === "sq" ? ["H", "M", "M", "E", "P", "S", "D"] : ["M", "T", "W", "T", "F", "S", "S"];
}

/** Explicit Albanian labels also work in browsers shipped without Albanian ICU data. */
export function localizedDate(language: Language, value: Date | string, timeZone: string, style: "month" | "day" | "full") {
  const date = new Date(value);
  if (language === "en") return new Intl.DateTimeFormat("en-GB", {
    timeZone, month: "long", ...(style !== "month" ? { weekday: "long" as const, day: "numeric" as const } : {}),
    ...(style !== "day" ? { year: "numeric" as const } : {}),
  }).format(date);
  const parts = new Intl.DateTimeFormat("en-GB", { timeZone, year: "numeric", month: "numeric", day: "numeric" }).formatToParts(date);
  const part = (name: string) => Number(parts.find(item => item.type === name)?.value);
  const year = part("year"), month = part("month"), day = part("day");
  const monthName = monthsSq[month - 1];
  if (style === "month") return `${monthName[0].toUpperCase()}${monthName.slice(1)} ${year}`;
  const weekday = weekdaysSq[new Date(Date.UTC(year, month - 1, day)).getUTCDay()];
  return `${weekday}, ${day} ${monthName}${style === "full" ? ` ${year}` : ""}`;
}
