export type Language = "sq" | "en";
export const languageCookie = "kreu-language";

// English is also the stable message key. Never translate stored form values,
// project slugs, customer input, contact addresses or third-party brand names.
export const albanian: Record<string, string> = {
  "KREU WEB. Built for progress.": "KREU WEB. Ndërtuar për progres.",
  "Kreu Web — Strategy, Design & Digital Development": "Kreu Web — Strategji, Dizajn & Zhvillim Digjital",
  "Kreu Web helps ambitious businesses build credible brands, high-performing websites, effective marketing and scalable digital products.": "Kreu Web ndihmon bizneset ambicioze të ndërtojnë marka të besueshme, website me performancë, marketing efektiv dhe produkte digjitale që shkallëzohen.",
  "Language": "Gjuha",
  "KREU WEB, home": "KREU WEB, kreu",
  "Primary navigation": "Navigimi kryesor",
  "Mobile navigation": "Navigimi në celular",
  "Footer navigation": "Navigimi në fund të faqes",
  "Navigation": "Navigimi",
  "Socials": "Rrjetet sociale",
  "Back to top": "Kthehu lart",
  "Work": "Projektet",
  "Services": "Shërbimet",
  "Contact": "Kontakt",
  "Open menu": "Hap menunë",
  "Close menu": "Mbyll menunë",
  "Close": "Mbyll",
  "Menu": "Menu",
  "Book a discovery call": "Rezervo një konsultë",
  "Build a business": "Ndërto një biznes",
  "people take seriously.": "që merret seriozisht.",
  "We position your business with clarity, credibility and authority so it is perceived at the level it aspires to.": "E pozicionojmë biznesin tuaj me qartësi, besueshmëri dhe autoritet që të perceptohet në nivelin që synon.",
  "View our work": "Shiko projektet",
  "Built for progress": "Ndërtuar për progres",
  "Every decision should serve the business.": "Çdo vendim duhet t’i shërbejë biznesit.",
  "Integrated strategy, design and technology for clearer positioning, sharper differentiation and greater competitive relevance.": "Strategji, dizajn dhe teknologji të integruara për një pozicionim më të qartë, diferencim më të dallueshëm dhe relevancë më të lartë në treg.",
  "Strategy & Design": "Strategji & Dizajn",
  "Web Development": "Web Development",
  "Marketing & SEO": "Marketing & SEO",
  "Software Systems": "Sisteme Software",
  "Connected services workflow": "Shërbime që funksionojnë së bashku",
  "Authority. Differentiation. Growth.": "Autoritet. Diferencim. Rritje.",
  "For the next stage.": "Për etapën e radhës.",
  "Make your business stand out where it matters.": "Bëje biznesin tënd të dallohet aty ku ka rëndësi.",
  "A considered digital presence designed to strengthen trust, increase relevance and create new opportunities for the business.": "Një prezencë digjitale e menduar për të forcuar besimin, për të rritur relevancën dhe për të krijuar mundësi të reja për biznesin.",
  "Design · Development · Growth · Software": "Dizajn · Zhvillim · Rritje · Software",
  "All rights reserved.": "Të gjitha të drejtat e rezervuara.",
  "For businesses defined by ambition.": "Për biznese me ambicie.",
  "Kreu Web on Instagram": "Kreu Web në Instagram",
  "Kreu Web": "Kreu Web",
  "A creative digital practice.": "Një praktikë digjitale krijuese.",
  "We create digital experiences people remember.": "Krijojmë përvoja digjitale që mbeten në mendje.",
  "Let’s create": "Le të krijojmë",
  "Kreu Web © 2026. Designed with intent.": "Kreu Web © 2026. Dizajnuar me qëllim.",
  "Projects": "Projektet",
  "About": "Rreth nesh",
  "Your next chapter": "Hapi juaj i radhës",
  "Selected website concepts": "Projekte të përzgjedhura",
  "Selected explorations": "Eksplorime të përzgjedhura",
  "Preview": "Shiko projektin",
  "Design concept": "Koncept dizajni",
  "Residential Real Estate": "Prona rezidenciale",
  "Mobile App / Software": "Aplikacion Mobile / Software",
  "Med Spa": "Klinikë estetike",
  "Hospitality": "Hoteleri & Restorante",
  "Car Rental": "Makina me qira",
  "A refined digital experience for modern residential developments.": "Një prezantim digjital i kuruar për rezidenca bashkëkohore.",
  "A considered mobile app concept for focused work, daily planning, and a little more clarity.": "Një aplikacion për më shumë përqendrim, planifikim të qartë dhe ditë më të organizuara.",
  "A calm, clinically precise experience for modern aesthetic care.": "Një përvojë e qetë dhe e qartë, që pasqyron kujdesin dhe saktësinë e mjekësisë estetike.",
  "A cinematic reservation experience built around appetite and atmosphere.": "Një përvojë rezervimi që përcjell shijen dhe atmosferën e restorantit.",
  "A booking experience engineered around performance and exceptional cars.": "Një përvojë rezervimi e kuruar për makina me performancë të jashtëzakonshme.",
  "Contemporary luxury residence architecture": "Arkitekturë bashkëkohore e një rezidence luksoze",
  "Residences": "Rezidencat",
  "Architecture": "Arkitektura",
  "Neighbourhood": "Zona",
  "Private viewings": "Vizita private",
  "Private residences · Tirana": "Rezidenca private · Tiranë",
  "Life, framed": "Jeta, në harmoni",
  "by architecture.": "me arkitekturën.",
  "Explore availability": "Shih rezidencat e lira",
  "Residence 04": "Rezidenca 04",
  "Three bedrooms · 186 m²": "Tri dhoma gjumi · 186 m²",
  "Now selling": "Në shitje",
  "Completion · Autumn 2027": "Përfundon · Vjeshtë 2027",
  "Still focus and planning app on a graphite smartphone in a softly lit charcoal workspace": "Aplikacioni Still për përqendrim dhe planifikim, në një telefon në ambient pune me dritë të butë",
  "Treatments": "Trajtimet",
  "Doctors": "Mjekët",
  "Philosophy": "Filozofia",
  "Book a consultation": "Rezervo një konsultë",
  "Skin intelligence · Tirana": "Kujdes për lëkurën · Tiranë",
  "Results you see.": "Rezultate të dukshme.",
  "Restraint you feel.": "Bukuri e natyrshme.",
  "Aesthetic medicine led by doctors and designed around skin health, natural expression and lasting confidence.": "Mjekësi estetike me shëndetin e lëkurës në qendër. Kujdes profesional që ruan shprehjen tuaj natyrale.",
  "Meet your skin": "Njih lëkurën tënde",
  "Portrait focused on natural skin": "Portret që vë në pah bukurinë natyrale të lëkurës",
  "Precision peel": "Peeling i personalizuar",
  "45 min · From €120": "45 min · Nga €120",
  "Contemporary fine dining room": "Ambient restoranti bashkëkohor",
  "Menu   Cellar   Story": "Menu   Verërat   Historia",
  "Reserve a table": "Rezervo një tavolinë",
  "Tirana · Dinner, Tuesday—Sunday": "Tiranë · Darkë, e martë—e diel",
  "The night": "Mbrëmja",
  "has a flavour.": "ka shijen e saj.",
  "Discover the menu": "Zbulo menunë",
  "Chef’s table": "Në tryezën e shefit",
  "Eight seasonal courses": "Tetë pjata të stinës",
  "Rruga e Durrësit, Tirana": "Rruga e Durrësit, Tiranë",
  "From 18:30 until late": "Nga ora 18:30 deri vonë",
  "Black performance car in motion": "Makinë sportive e zezë në lëvizje",
  "Fleet": "Makinat",
  "Membership": "Anëtarësimi",
  "Destinations": "Destinacionet",
  "Reserve": "Rezervo",
  "Porsche Panamera Turbo · Tirana": "Porsche Panamera Turbo · Tiranë",
  "Performance,": "Performancë,",
  "on your terms.": "sipas ritmit tënd.",
  "Configure your drive": "Zgjidh udhëtimin tënd",
  "From €680 / day": "Nga €680 / ditë",
  "24 / 7 concierge": "Asistencë 24 / 7",
  "Also available": "Gjithashtu në dispozicion",
  "First class.": "Klas i parë.",
  "Every mile.": "Në çdo kilometër.",
  "Your next drive": "Udhëtimi yt i radhës",
  "Explore the fleet": "Shih makinat",
  "Play First Class motion": "Luaj animacionin e First Class",
  "Pause First Class motion": "Ndalo animacionin e First Class",
  "Opening booking…": "Po hapet rezervimi…",
  "Close booking": "Mbyll rezervimin",
  "Discovery call": "Konsultë",
  "Project request": "Kërkesë projekti",
  "Private consultation": "Konsultë private",
  "Start something worth building.": "Nis diçka që ia vlen të ndërtohet.",
  "Consultation overview": "Përmbledhja e konsultës",
  "Consultation brief": "Përmbledhje e projektit",
  "Consultation received": "Kërkesa u pranua",
  "A focused beginning for serious work.": "Një fillim i qartë për një bashkëpunim serioz.",
  "Six considered questions help us understand the business, the ambition and whether we are the right fit.": "Gjashtë pyetje të menduara na ndihmojnë të kuptojmë biznesin, ambicien dhe nëse jemi partneri i duhur.",
  "Reviewed privately by Kreu.": "Shqyrtohet privatisht nga Kreu.",
  "Business": "Biznesi",
  "Website": "Website",
  "WhatsApp": "WhatsApp",
  "Investment": "Investimi",
  "Project": "Projekti",
  "Confirmed": "Konfirmuar",
  "Booking progress": "Ecuria e rezervimit",
  "Project request progress": "Ecuria e kërkesës",
  "What’s your name?": "Si quheni?",
  "What’s your full name?": "Si quheni?",
  "What’s your email address?": "Cili është emaili juaj?",
  "What’s your business called?": "Si quhet biznesi juaj?",
  "Do you currently have a website?": "A keni aktualisht një website?",
  "What’s your current monthly business revenue?": "Sa është xhiroja mujore e biznesit tuaj?",
  "What should we know before the call?": "Çfarë duhet të dimë para se të flasim?",
  "What is your estimated investment?": "Sa planifikoni të investoni?",
  "What investment range are you considering?": "Çfarë niveli investimi po konsideroni?",
  "What’s your WhatsApp number?": "Cili është numri juaj në WhatsApp?",
  "Tell us briefly about your project.": "Na tregoni shkurt për projektin.",
  "Tell us about your project. What do you want to achieve?": "Na tregoni për projektin. Çfarë dëshironi të arrini?",
  "How did you hear about us?": "Si dëgjuat për ne?",
  "Choose a time that works.": "Zgjidhni orarin që ju përshtatet.",
  "Full name": "Emri dhe mbiemri",
  "Your full name": "Emri dhe mbiemri juaj",
  "Name": "Emri",
  "Your name": "Emri juaj",
  "Email address": "Adresa e emailit",
  "Business name": "Emri i biznesit",
  "Your business name": "Emri i biznesit tuaj",
  "Yes": "Po",
  "No": "Jo",
  "Website URL": "Adresa e website-it",
  "Country code": "Prefiksi",
  "WhatsApp number": "Numri në WhatsApp",
  "Your WhatsApp number": "Numri juaj në WhatsApp",
  "yourbusiness.com": "biznesijuaj.com",
  "you@business.com": "ju@biznesi.com",
  "Current monthly business revenue": "Të ardhurat mujore të biznesit",
  "Estimated investment": "Investimi i parashikuar",
  "Under €10k": "Nën €10k",
  "€10k–€50k": "€10.000–€50.000",
  "€50k–€100k": "€50.000–€100.000",
  "€100k+": "€100.000+",
  "€2,000–€5,000": "€2.000–€5.000",
  "€5,000–€10,000": "€5.000–€10.000",
  "€10,000–€25,000": "€10.000–€25.000",
  "€25,000+": "€25.000+",
  "Investment range": "Niveli i investimit",
  "A little context": "Pak kontekst",
  "Project details": "Rreth projektit",
  "Optional": "Opsionale",
  "A few lines about the business, what’s changing, and what you want Kreu to help you achieve.": "Na tregoni shkurt për biznesin, çfarë po ndryshon dhe çfarë doni që Kreu t’ju ndihmojë të arrini.",
  "What are you looking to build or improve?": "Çfarë dëshironi të ndërtoni ose përmirësoni?",
  "Instagram": "Instagram",
  "TikTok": "TikTok",
  "LinkedIn": "LinkedIn",
  "Google referral": "Google / Rekomandim",
  "Other": "Tjetër",
  "Back": "Kthehu",
  "Book discovery call": "Rezervo konsultën",
  "Send enquiry": "Dërgo kërkesën",
  "Apply to Work With Us": "Apliko për bashkëpunim",
  "Sending your request…": "Po dërgojmë kërkesën tuaj…",
  "Continue": "Vazhdo",
  "Thank you.": "Faleminderit.",
  "We’ll review your details and be in touch by email.": "Do t’i shqyrtojmë të dhënat tuaja dhe do t’ju kontaktojmë me email.",
  "We’ll review your details and reply by email.": "Do t’i shqyrtojmë të dhënat tuaja dhe do t’ju përgjigjemi me email.",
  "Thank you. We’ve received your project request.": "Faleminderit. E kemi pranuar kërkesën tuaj për projekt.",
  "Our team will review the information you submitted and we’ll contact you directly on WhatsApp to discuss the next steps.": "Ekipi ynë do t’i shqyrtojë të dhënat që keni dërguar dhe do t’ju kontaktojë drejtpërdrejt në WhatsApp për hapat e radhës.",
  "A focused first step for your next project.": "Një hap i qartë drejt projektit tuaj të radhës.",
  "A few details. Then we talk about where your business can go next.": "Disa detaje. Pastaj flasim për hapin e radhës të biznesit tuaj.",
  "A considered start to something better.": "Një hap i menduar mirë.",
  "Back to Kreu": "Kthehu te Kreu",
  "Please enter your name.": "Shkruani emrin tuaj.",
  "Please enter a valid email address.": "Shkruani një adresë emaili të vlefshme.",
  "Please enter your business name.": "Shkruani emrin e biznesit.",
  "Please enter a valid WhatsApp number.": "Shkruani një numër të vlefshëm WhatsApp.",
  "We couldn’t send your project request. Please try again.": "Nuk arritëm ta dërgojmë kërkesën tuaj për projekt. Provoni sërish.",
  "Choose Yes or No to continue.": "Zgjidhni Po ose Jo për të vazhduar.",
  "Enter your website address, for example yourbusiness.com.": "Shkruani adresën e website-it, për shembull biznesijuaj.com.",
  "Choose a revenue range.": "Zgjidhni nivelin e të ardhurave.",
  "Choose an investment range.": "Zgjidhni nivelin e investimit.",
  "Choose how you heard about us.": "Zgjidhni si dëgjuat për ne.",
  "Please keep your notes under 2,000 characters.": "Ju lutemi, shkruani jo më shumë se 2 000 karaktere.",
  "🇦🇱 Albania +355": "🇦🇱 Shqipëri +355",
  "🇽🇰 Kosovo +383": "🇽🇰 Kosovë +383",
  "🇲🇰 North Macedonia +389": "🇲🇰 Maqedonia e Veriut +389",
  "🇲🇪 Montenegro +382": "🇲🇪 Mali i Zi +382",
  "🇩🇪 Germany +49": "🇩🇪 Gjermani +49",
  "🇨🇭 Switzerland +41": "🇨🇭 Zvicër +41",
  "🇦🇹 Austria +43": "🇦🇹 Austri +43",
  "🇮🇹 Italy +39": "🇮🇹 Itali +39",
  "🇬🇧 United Kingdom +44": "🇬🇧 Mbretëria e Bashkuar +44",
  "🇺🇸 United States +1": "🇺🇸 Shtetet e Bashkuara +1",
};

export function translate(language: Language, message: string): string {
  return language === "sq" ? albanian[message] ?? message : message;
}
